name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm test

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker info

      - name: Build and Push Docker Image
        run: |
          docker build -t agarwalprateek666/weather-web:latest .
          docker tag agarwalprateek666/weather-web:latest agarwalprateek666/weather-web:v1
          docker push agarwalprateek666/weather-web:latest
          docker push agarwalprateek666/weather-web:v1
  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: |
          curl -fsSL cli.new | sh
          export PATH=$HOME/.railway/bin:$PATH

      - name: Authenticate Railway CLI
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: railway up --service weather-web
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm test

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker info

      - name: Build and Push Docker Image
        run: |
          docker build -t agarwalprateek666/weather-web:latest .
          docker tag agarwalprateek666/weather-web:latest agarwalprateek666/weather-web:v1
          docker push agarwalprateek666/weather-web:latest
          docker push agarwalprateek666/weather-web:v1

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: |
          curl -fsSL cli.new | sh
          export PATH=$HOME/.railway/bin:$PATH

      - name: Authenticate Railway CLI
        run: echo ${{ secrets.RAILWAY_TOKEN }} | railway login

      - name: Deploy to Railway
        run: railway up --service weather-web
